import { Member, Task } from './types';

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'm-1',
    name: 'Nguyễn Thị Hương',
    email: 'huong.nguyen@company.vn',
    role: 'Trưởng Dự Án (Project Manager)',
    department: 'Quản lý dự án',
    avatar: 'H',
    color: 'from-pink-500 to-rose-600',
    phone: '0901 234 567',
    joinedDate: '2025-01-10',
  },
  {
    id: 'm-2',
    name: 'Trần Minh Tuấn',
    email: 'tuan.tran@company.vn',
    role: 'Kỹ sư Frontend (Senior)',
    department: 'Kỹ thuật Công nghệ',
    avatar: 'T',
    color: 'from-pink-600 to-fuchsia-600',
    phone: '0912 345 678',
    joinedDate: '2025-02-15',
  },
  {
    id: 'm-3',
    name: 'Lê Thuỳ Trang',
    email: 'trang.le@company.vn',
    role: 'Chuyên viên UI/UX Designer',
    department: 'Thiết kế sản phẩm',
    avatar: 'Tr',
    color: 'from-rose-400 to-pink-500',
    phone: '0933 456 789',
    joinedDate: '2025-03-01',
  },
  {
    id: 'm-4',
    name: 'Phạm Đức Anh',
    email: 'anh.pham@company.vn',
    role: 'Kỹ sư Backend & Database',
    department: 'Kỹ thuật Công nghệ',
    avatar: 'A',
    color: 'from-pink-500 to-purple-500',
    phone: '0944 567 890',
    joinedDate: '2025-04-12',
  },
  {
    id: 'm-5',
    name: 'Hoàng Mai Phương',
    email: 'phuong.hoang@company.vn',
    role: 'Chuyên viên Kiểm thử (QA Tester)',
    department: 'Đảm bảo chất lượng',
    avatar: 'P',
    color: 'from-rose-500 to-pink-600',
    phone: '0988 765 432',
    joinedDate: '2025-05-20',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-101',
    title: 'Thiết kế giao diện Mobile App phiên bản 2.0 (Figma)',
    description: 'Nghiên cứu trải nghiệm người dùng và hoàn thiện toàn bộ bộ UI kit hệ thống tone màu hồng pastel, luồng onboarding và trang quản lý công việc.',
    assignedMemberIds: ['m-3', 'm-1'],
    startDate: '2026-08-25',
    dueDate: '2026-09-10',
    priority: 'high',
    status: 'review',
    reportLink: 'https://figma.com/file/pinktask-ui-design-v2-mockup',
    reportNotes: 'Đã hoàn thành 100% 24 màn hình chính, bao gồm Dark Mode và Light Mode tone hồng hoa anh đào. Đã tạo Prototype tương tác.',
    reportSubmittedAt: '2026-09-04 15:30',
    comments: [
      {
        id: 'c-1',
        taskId: 'task-101',
        authorId: 'm-3',
        authorName: 'Lê Thuỳ Trang',
        authorRole: 'UI/UX Designer',
        authorAvatar: 'Tr',
        content: 'Em đã nộp file Figma kết quả theo link ở trên. Mọi người kiểm tra luồng tạo công việc mới và cho em xin phản hồi nhé!',
        createdAt: '2026-09-04 15:35',
        tag: 'feedback',
      },
      {
        id: 'c-2',
        taskId: 'task-101',
        authorId: 'm-1',
        authorName: 'Nguyễn Thị Hương',
        authorRole: 'Project Manager',
        authorAvatar: 'H',
        content: 'Giao diện màu hồng rất sang trọng và dịu mắt! Nhờ Trang chỉnh lại font chữ ở bảng chi tiết task lên 15px để dễ nhìn hơn nhé.',
        createdAt: '2026-09-05 09:20',
        tag: 'revision',
      },
      {
        id: 'c-3',
        taskId: 'task-101',
        authorId: 'm-3',
        authorName: 'Lê Thuỳ Trang',
        authorRole: 'UI/UX Designer',
        authorAvatar: 'Tr',
        content: 'Dạ em đã cập nhật font chữ và kích thước theo góp ý của chị Hương rồi ạ! Link Figma tự động đồng bộ.',
        createdAt: '2026-09-05 11:45',
        tag: 'feedback',
      },
      {
        id: 'c-4',
        taskId: 'task-101',
        authorId: 'm-1',
        authorName: 'Nguyễn Thị Hương',
        authorRole: 'Project Manager',
        authorAvatar: 'H',
        content: 'Tuyệt vời, duyệt thiết kế này nhé! Tuấn có thể bắt đầu cắt giao diện.',
        createdAt: '2026-09-05 14:10',
        tag: 'approved',
      },
    ],
    createdAt: '2026-08-25 08:00',
  },
  {
    id: 'task-102',
    title: 'Phát triển API phân quyền và giao việc cho thành viên',
    description: 'Xây dựng các endpoint RESTful cho phép gán thành viên vào công việc, thiết lập thời hạn bắt đầu - kết thúc và lưu link báo cáo kết quả.',
    assignedMemberIds: ['m-4'],
    startDate: '2026-09-01',
    dueDate: '2026-09-12',
    priority: 'urgent',
    status: 'in_progress',
    reportLink: 'https://documenter.getpostman.com/view/pinktask-api-docs-v1',
    reportNotes: 'Đang triển khai Swagger documentation và kiểm thử đơn vị các route phân quyền.',
    reportSubmittedAt: '2026-09-05 18:00',
    comments: [
      {
        id: 'c-5',
        taskId: 'task-102',
        authorId: 'm-4',
        authorName: 'Phạm Đức Anh',
        authorRole: 'Backend Developer',
        authorAvatar: 'A',
        content: 'Link Postman docs bản nháp đã cập nhật ở trên. Tuấn Frontend test thử route /api/tasks nhé.',
        createdAt: '2026-09-05 18:15',
        tag: 'general',
      },
      {
        id: 'c-6',
        taskId: 'task-102',
        authorId: 'm-2',
        authorName: 'Trần Minh Tuấn',
        authorRole: 'Senior Frontend',
        authorAvatar: 'T',
        content: 'Các route response chuẩn JSON, kết nối mượt mà nhé anh Anh. Lưu ý hỗ trợ thêm mảng link đính kèm nếu cần.',
        createdAt: '2026-09-06 08:40',
        tag: 'feedback',
      },
    ],
    createdAt: '2026-09-01 09:00',
  },
  {
    id: 'task-103',
    title: 'Tích hợp giao diện Quản lý Thành viên và Sidebar',
    description: 'Cắt giao diện sidebar chức năng bên trái với hiệu ứng trượt mượt mà, thanh điều hướng và hiển thị danh sách thành viên trực quan.',
    assignedMemberIds: ['m-2'],
    startDate: '2026-09-03',
    dueDate: '2026-09-09',
    priority: 'high',
    status: 'in_progress',
    reportLink: 'https://github.com/company-team/pinktask-frontend/pull/42',
    reportNotes: 'Đã tạo Pull Request #42 với đầy đủ responsive mobile và desktop, theme màu hồng tinh tế.',
    reportSubmittedAt: '2026-09-06 14:00',
    comments: [
      {
        id: 'c-7',
        taskId: 'task-103',
        authorId: 'm-2',
        authorName: 'Trần Minh Tuấn',
        authorRole: 'Senior Frontend',
        authorAvatar: 'T',
        content: 'Link PR ở trên ạ. Nhờ QA test giúp trên trình duyệt Safari và Chrome.',
        createdAt: '2026-09-06 14:05',
        tag: 'feedback',
      },
    ],
    createdAt: '2026-09-03 10:00',
  },
  {
    id: 'task-104',
    title: 'Kiểm thử hộp đen tính năng bình luận báo cáo kết quả',
    description: 'Kiểm tra độ trễ hiển thị bình luận, quyền chỉnh sửa/xóa bình luận và tính hợp lệ của đường dẫn URL báo cáo kết quả công việc.',
    assignedMemberIds: ['m-5'],
    startDate: '2026-09-08',
    dueDate: '2026-09-15',
    priority: 'medium',
    status: 'todo',
    reportLink: '',
    comments: [],
    createdAt: '2026-09-04 11:00',
  },
  {
    id: 'task-105',
    title: 'Biên soạn tài liệu hướng dẫn quy trình báo cáo kết quả',
    description: 'Xây dựng slide và checklist chuẩn hóa việc nộp link báo cáo kết quả công việc (Google Drive, Notion, GitHub) cho các phòng ban.',
    assignedMemberIds: ['m-1'],
    startDate: '2026-08-20',
    dueDate: '2026-08-30',
    priority: 'low',
    status: 'completed',
    reportLink: 'https://docs.google.com/presentation/d/pinktask-guidelines-2026',
    reportNotes: 'Tài liệu đã được phát hành cho toàn thể nhân sự trong buổi họp đầu tháng.',
    reportSubmittedAt: '2026-08-29 16:00',
    comments: [
      {
        id: 'c-8',
        taskId: 'task-105',
        authorId: 'm-1',
        authorName: 'Nguyễn Thị Hương',
        authorRole: 'Project Manager',
        authorAvatar: 'H',
        content: 'Đã hoàn thành và chuyển giao tài liệu hướng dẫn.',
        createdAt: '2026-08-29 16:10',
        tag: 'approved',
      },
    ],
    createdAt: '2026-08-20 08:30',
  },
];
